spring:
    application:
        name: categoria-service
    datasource:
        url: jdbc:mysql://localhost:3306/biblioteca
        username: root
        password: master
    jpa:
        hibernate:
            ddlAuto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        showSql: true

server:
  port: 6065
  
eureka:
    client:
        serviceUrl: 
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true
